/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressFormDialog: typeof import('./src/components/address/AddressFormDialog.vue')['default']
    AdminLayout: typeof import('./src/components/layout/AdminLayout.vue')['default']
    AppendReviewDialog: typeof import('./src/components/review/AppendReviewDialog.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AuthDialog: typeof import('./src/components/AuthDialog.vue')['default']
    AvatarUpload: typeof import('./src/components/AvatarUpload.vue')['default']
    BlacklistDialog: typeof import('./src/components/chat/BlacklistDialog.vue')['default']
    BlockBanner: typeof import('./src/components/chat/BlockBanner.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ConversationItem: typeof import('./src/components/chat/ConversationItem.vue')['default']
    CreateOrderDialog: typeof import('./src/components/order/CreateOrderDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    OnlineDot: typeof import('./src/components/chat/OnlineDot.vue')['default']
    OrderCardMessage: typeof import('./src/components/chat/OrderCardMessage.vue')['default']
    OrderPickerDialog: typeof import('./src/components/chat/OrderPickerDialog.vue')['default']
    PaymentDialog: typeof import('./src/components/order/PaymentDialog.vue')['default']
    ProductAuditDialog: typeof import('./src/components/admin/ProductAuditDialog.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductCardMessage: typeof import('./src/components/chat/ProductCardMessage.vue')['default']
    ProductPickerDialog: typeof import('./src/components/chat/ProductPickerDialog.vue')['default']
    PublishProductDialog: typeof import('./src/components/product/PublishProductDialog.vue')['default']
    QuickReplyPanel: typeof import('./src/components/chat/QuickReplyPanel.vue')['default']
    ReadStatusBadge: typeof import('./src/components/chat/ReadStatusBadge.vue')['default']
    ReviewCard: typeof import('./src/components/review/ReviewCard.vue')['default']
    ReviewFormDialog: typeof import('./src/components/review/ReviewFormDialog.vue')['default']
    ReviewList: typeof import('./src/components/review/ReviewList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/chat/SearchPanel.vue')['default']
    TypingIndicator: typeof import('./src/components/chat/TypingIndicator.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
